// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFHtER5PjK9iePcA_VwVV1sdvDE27CuL0',
    appId: '1:266747151093:web:2afc72a8c8c9ef86fff2dc',
    messagingSenderId: '266747151093',
    projectId: 'fixora-bb37d',
    authDomain: 'fixora-bb37d.firebaseapp.com',
    storageBucket: 'fixora-bb37d.firebasestorage.app',
    databaseURL: 'https://fixora-bb37d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHtER5PjK9iePcA_VwVV1sdvDE27CuL0',
    appId: '1:266747151093:android:bcb1ea81a81b0f0214fbbc',
    messagingSenderId: '266747151093',
    projectId: 'fixora-bb37d',
    storageBucket: 'fixora-bb37d.firebasestorage.app',
    databaseURL: 'https://fixora-bb37d-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHtER5PjK9iePcA_VwVV1sdvDE27CuL0',
    appId: '1:266747151093:ios:2213c9fabaec34d4fff2dc',
    messagingSenderId: '266747151093',
    projectId: 'fixora-bb37d',
    storageBucket: 'fixora-bb37d.firebasestorage.app',
    iosBundleId: 'com.example.fixora',
    databaseURL: 'https://fixora-bb37d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHtER5PjK9iePcA_VwVV1sdvDE27CuL0',
    appId: '1:266747151093:ios:2213c9fabaec34d4fff2dc',
    messagingSenderId: '266747151093',
    projectId: 'fixora-bb37d',
    storageBucket: 'fixora-bb37d.firebasestorage.app',
    iosBundleId: 'com.example.fixora',
    databaseURL: 'https://fixora-bb37d-default-rtdb.firebaseio.com',
  );
}
